extension/keysocket-bop.js, extension/manifest.json
Adding support for bop.fm website media controls.
=> Adding bop.fm support

README.md, extension/keysocket-gaana.js, extension/keysocket-saavn.js, extension/manifest.json
gaana.com and Saavn.com are Indian Music websites.
=> add support for gaana.com

README.md, extension/keysocket-ok.js, extension/manifest.json
Ok.ru music service support.
I recreated this cause merge problems
=> Adding Ok.ru service

extension/keysocket-youtube.js
For me youtube doesn't have the playlist with player controls by default (and if I visit in incognito mode it seems the same). This will directly use the HTML5 controls for NEXT, PLAY, and PREV.
=> Youtube update

README.md, extension/keysocket-superplayer.js, extension/manifest.json
[Superplayer](http://superplayer.fm) is a brazilian online radio.
=> Add support for Superplayer

README.md, extension/keysocket-pocketcasts.js, extension/manifest.json
=> Added support for PocketCasts

extension/keysocket-pocketcasts.js
Removed unnecessary function isVisible()
=> Removed unnecessary function isVisible()

README.md, extension/keysocket-zvooq.js, extension/manifest.json
Supports [zvooq](zvooq.ru) music player
=> Adds zvooq adapter

README.md, extension/keysocket-somafm.js, extension/manifest.json
Add support for SomaFM web player at somafm.com.
=> Add SomaFM Support

extension/keysocket-youtube.js
- Added new query class
- Kept older class for backward compatibility
=> Fix youtube for new layout

extension/keysocket-yandex-radio.js, extension/manifest.json
=> Adding Yandex.radio

extension/keysocket-slacker.js
=> Update for new Slacker player

README.md
=> remove grooveshark

README.md, extension/keysocket-livestream.js, extension/keysocket-twitch.js, extension/keysocket-ustream.js, extension/manifest.json
Probably this is not the best way to do this, but it was the only way that I could get working.
=> Support for Ustream, Twitch.tv and Livestream.com

README.md, extension/keysocket-groovemusic.js, extension/manifest.json
Microsoft changed the branding and url of their music service.
=> Update Xbox Music to Groove Music

extension/keysocket-amazon-cloud-player.js, extension/manifest.json
This should fix the issues with Amazon's latest cloud music player. Have tested on two different systems with success.
=> Fix Amazon's cloud music player.

extension/keysocket-spotify.js
I haven't fully tested it, also I don't know if it's been rolled out everywhere already or just a/b tests or certain countries.
=> Updated to spotify's new layout

extension/keysocket-vkontakte.js
=> Fix new VK.com

README.md, extension/keysocket-prostopleer.js, extension/manifest.json
=> Prostopleer added

README.md, extension/keysocket-noon-pacific.js, extension/manifest.json, extension/shared.js
This PR is based on https://github.com/borismus/keysocket/pull/142 with conflict resolved
=> Add Noon Pacific (noonpacific.com)

README.md
I noticed that www.Relax-Hub.com made use of a little hidden API, so I thought to bring @feedbee's wonderful feature, and use of it, to light!
=> Add rough API documentation

README.md
=> Update Supported Sites list

extension/media-control-api.js
=> Update `media-control-api.js` to Web Page Control API v1.0

README.md, extension/keysocket-eighttracks.js, extension/manifest.json
Great project, guys. Like to contribute.
Added [8tracks.com](http://8tracks.com) support. 8tracks has different selectors for play/pause and requires to change playlist after couple of skips, so skip track and skip playlist has different selectors too, thats why the code not as simple as for other players.
=> 8tracks.com support added

README.md, extension/keysocket-myspace.js, extension/manifest.json
Adding support for Myspace music player on https://myspace.com/
=> Add support for Myspace

extension/keysocket-qobuz.js, extension/manifest.json
Hello,
I just added the Qobuz (http://www.qobuz.com/) web player (http://player.qobuz.com/).
Thanks for your work !
=> add Qobuz web player support

extension/keysocket-xfinity.js, extension/manifest.json
Add play/pause support for tv.xfinity.com
=> Add comcast/xfinity support

README.md, extension/keysocket-iloveradio.js, extension/keysocket-tunein.js, extension/manifest.json
Deciding that moving forward is our best option, I went ahead and fixed the manifest that was causing a conflict in #191.  ;)
=> Add tunein.com and iloveradio.de support (fixes conflicts in #191)

README.md, extension/keysocket-iloveradio.js, extension/keysocket-tunein.js, extension/manifest.json
Verified working on my local system
=> added Tunein.com support

README.md, extension/keysocket-163.js, extension/manifest.json
=> Update extension for 163 Music

README.md, extension/keysocket-supersport.js, extension/manifest.json
Added support for www.supersport.com
You need an active paid subscription for this service
Only play/Pause functionality is available on the website
=> Added support for www.supersport.com

extension/keysocket-pocketcasts.js, extension/manifest.json
Tested against: Version 2.0 Build 22
Fixes: #243
=> Add support for the new beta of Pocket Casts

extension/keysocket-pocketcasts.js
The media buttons for the Pocket Casts beta where changed from divs to buttons.
=> Fixed support for Pocket Casts beta

extension/keysocket-pluralsight.js, extension/manifest.json
can be tested on a free course, like this one: https://app.pluralsight.com/player?name=get-involved-m1-intro&clip=0&course=get-involved&author=rob-conery
=> add supprt for pluralsight

extension/keysocket-youtube-music.js, extension/manifest.json
Tested, does not interfere with regular youtube controls
=> Added YouTube Music support

extension/keysocket-apple-developer.js, extension/keysocket-overcast.js, extension/manifest.json
I use Overcast daily and really wanted Keysocket support. I use this daily, so I can confirm that it works.
=> Add proper, tested support for Overcast.fm

extension/keysocket-metopera.js, extension/manifest.json
Support for https://www.metopera.org/Season/On-Demand/
=> Add support for Met Opera Season On-Demand

README.md, extension/keysocket-prostopleer.js, extension/manifest.json
The service is no longer online
=> Remove prostopleer

README.md, extension/keysocket-coursera.js, extension/manifest.json
This adds support for switching between Coursera course items and controlling lecture playback.
=> Add support for Coursera

README.md, extension/keysocket-ibizasonica.js, extension/manifest.json
Added support for this streaming site.
=> ibizasonica.com

extension/keysocket-spotify.js
Added stop media key to spotify service.
=> Add stop functionality to spotify

extension/keysocket-linkedin-learning.js, extension/manifest.json
This adds support for LinkedIn Learning.
Play, Next and Previous all work correctly (tested with Apple wired keyboard on Windows 10 64-Bit with Chrome 68). Note that Pause does not work, I couldn't figure it out.. maybe someone else can?
=> LinkedIn learning

README.md, extension/keysocket-iplayer.js, extension/keysocket-openload.js, extension/keysocket-plex.js, extension/manifest.json, extension/plugin-api.js
Fixes support for buttons on Plex and added support for openload
=> Fix Plex and openload support

README.md, extension/keysocket-noisli.js, extension/manifest.json
Supports play-pause.
Only tested without creating an account, saw it has different CSS selectors when user is logged in.
=> Add noisli.com support

extension/keysocket-mx3creations.js, extension/manifest.json
Wasn't able to test this, but it should work just fine
=> Add mx3creations.com

README.md, extension/keysocket-jamendo.js, extension/manifest.json
Also fix existing errors in manifest. This diff will be best viewed with `git diff -w` to ignore the changing of tabs to spaces.
=> Support jamendo.com.
